apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: shadowman-the-bot bot
      tags: ruby, slack
    labels:
      app: shadowman-the-bot
    name: shadowman-the-bot

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: shadowman-the-bot
    name: shadowman-the-bot
  spec:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 1
    runPolicy: 'Serial' 
    
    triggers:
    - github:
        secret: shadowman-the-bot
      type: GitHub
    - generic:
        secret: shadowman-the-bot
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
    source:
      git:
        uri: https://github.com/shadowman-the-bot/shadowman-the-bot
        ref: master
      type: Git
    
    strategy:
      sourceStrategy:
        env:
          #- name: SLACK_TOKEN
          #  valueFrom:
          #    secretKeyRef:
          #      key: slack-token
          #      name: shadowman-the-bot-secrets
          #
          #- name: DATABASE_HOST
          #  value: 'redis'
          #- name: DATABASE_PORT
          #  value: '6379'
          #- name: DATABASE_SERVICE_NAME
          #  value: 'redis'
          
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'ruby:2.5'
          
      type: Source
        
    output:
      to:
        kind: ImageStreamTag
        name: 'shadowman-the-bot:latest'
