apiVersion: v1
items:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: shadowman-the-bot
    labels:
      app: shadowman-the-bot
  spec:
    replicas: 1
    selector:
      name: shadowman-the-bot
    strategy:
      type: Rolling
      #rollingParams:
      #  updatePeriodSeconds: 1 
      #  intervalSeconds: 1 
      #  timeoutSeconds: 120 
      #  maxSurge: "20%" 
      #  maxUnavailable: "10%" 
      #  pre: {} 
      #  post: {}
        
    template:
      metadata:
        name: shadowman-the-bot
        labels:
          name: shadowman-the-bot
          app: shadowman-the-bot
      spec:
        containers:
          - env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: shadowman-the-bot-secrets
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: shadowman-the-bot-secrets
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: shadowman-the-bot-secrets
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: shadowman-the-bot-secrets
            
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: slack-client-id
                  name: shadowman-the-bot-secrets
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: slack-client-secret
                  name: shadowman-the-bot-secrets
            
            - name: RACK_ENV
              value: 'production'
            - name: DATABASE_SERVICE_NAME
              value: 'mongodb'
              
            image: ''
            name: shadowman-the-bot
            ports:
              - containerPort: 8080

            #livenessProbe:
            #  httpGet:
            #    path: /status/alive
            #    port: 8080
            #  initialDelaySeconds: 60
            #  timeoutSeconds: 3
            #
            #readinessProbe:
            #  httpGet:
            #    path: /status/ready
            #    port: 8080
            #  initialDelaySeconds: 30
            #  timeoutSeconds: 5
            #
            resources:
              limits:
                memory: '512Mi'

    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - shadowman-the-bot
          from:
            kind: ImageStreamTag
            name: 'shadowman-the-bot:latest'
        type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}", "kind": "Service"}]'
    name: shadowman-the-bot
    labels:
      app: shadowman-the-bot
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      name: shadowman-the-bot

- apiVersion: v1
  kind: Route
  metadata:
    name: www
    labels:
      app: shadowman-the-bot
  spec:
    #host: 'www.example.com'
    to:
      kind: Service
      name: shadowman-the-bot
      
kind: List
metadata: []