apiVersion: v1
items:

- kind: DeploymentConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Defines how to deploy the database
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'redis'
    labels:
      app: shadowman-the-bot
  spec:
    replicas: 1
    selector:
      name: 'redis'
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: 'redis'
        name: 'redis'
      spec:
        containers:
          - env:
            # database, user etc
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: shadowman-the-bot-secrets
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: shadowman-the-bot-secrets
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: shadowman-the-bot-secrets
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: shadowman-the-bot-secrets
                  
            - name: DATABASE_SERVICE_NAME
              value: 'redis'
            
            image: ' '
            name: redis
            ports:
              - containerPort: 6379

            resources:
              limits:
                memory: '512Mi'
            
            volumeMounts:
              - mountPath: /var/lib/redisdata
                name: 'redis-data'
        volumes:
          - name: 'redis-data'
            persistentVolumeClaim:
              claimName: 'database'
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - redis
          from:
            kind: ImageStreamTag
            name: 'rhscl/redis-5-rhel7'
            namespace: 'openshift'
        type: ImageChange

- kind: Service
  apiVersion: "v1"
  metadata:
    annotations:
      description: Exposes the database server
    name: 'redis'
    labels:
      app: shadowman-the-bot
  spec:
    ports:
      - name: 'db'
        port: 6379
        targetPort: 6379
    selector:
      name: 'redis'

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'database'
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '1Gi'

kind: List
metadata: []